name: Build macOS & Linux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxkbcommon-dev ninja-build

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.2'
        modules: 'qtnetworkauth qt5compat qtnetworkinformation'

    - name: Build
      run: |
        mkdir build-release
        cd build-release
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=AppDist ..
        ninja install

    - name: Package macOS DMG
      if: matrix.os == 'macos-latest'
      run: |
        cd build-release
        macdeployqt AppDist/appHogrin.app -qmldir=../src/ui/qml -dmg
        mv AppDist/appHogrin.dmg ../Hogrin-macOS.dmg

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Hogrin-${{ matrix.os }}
        path: |
          Hogrin-macOS.dmg
          build-release/AppDist/
